export type Lesson = {
  id: string;
  title: string;
  week: number;
  keys: string;
  words: string[];
  focus: string;
};

export type KeyMeta = {
  label: string;
  finger: string;
  home?: boolean;
};

export const SESSION_SECONDS = 600;
export const TARGET_WPM = 40;
export const TARGET_ACCURACY = 95;

export const LESSONS: Lesson[] = [
  {
    id: "w1-home",
    title: "Home row asdf jkl;",
    week: 1,
    keys: "asdfjkl;",
    words: [
      "asdf",
      "jkl;",
      "asdf jkl;",
      "fj",
      "dk",
      "sl",
      "a;",
      "ask",
      "dad",
      "fad",
      "lad",
      "fall",
      "all",
      "sad",
      "flask",
      "salad",
      "falls",
      "adds",
      "lass",
    ],
    focus: "Park index fingers on F and J. Those two keys have bumps. Eyes stay on the screen.",
  },
  {
    id: "w1-space",
    title: "Home row + space",
    week: 1,
    keys: "asdfjkl; ",
    words: [
      "a s d f",
      "j k l ;",
      "as df",
      "jk l;",
      "ask dad",
      "fall lad",
      "sad flask",
      "all salad",
      "adds falls",
    ],
    focus: "Thumbs tap space. Fingers never leave home except the one key you need.",
  },
  {
    id: "w1-gh",
    title: "Index stretch G and H",
    week: 1,
    keys: "asdfghjkl;",
    words: [
      "fg",
      "jh",
      "gag",
      "had",
      "flag",
      "glad",
      "half",
      "dash",
      "glass",
      "flash",
      "slash",
      "gash",
      "hall",
      "has",
      "had a glass",
    ],
    focus: "F-finger reaches G. J-finger reaches H. Return home after every key.",
  },
  {
    id: "w1-words",
    title: "Home-row words",
    week: 1,
    keys: "asdfghjkl;",
    words: [
      "a sad lad",
      "ask dad",
      "a flask",
      "glad flags",
      "half a glass",
      "fall salad",
      "a lag",
      "had a fall",
      "slash a flag",
    ],
    focus: "Accuracy over speed. If a line is under 95% correct, type it again slower.",
  },
  {
    id: "w2-ei",
    title: "Middle fingers E and I",
    week: 2,
    keys: "asdfghjkl;ei",
    words: [
      "fed",
      "led",
      "kid",
      "lid",
      "said",
      "desk",
      "like",
      "file",
      "idea",
      "slide",
      "field",
      "a like file",
      "she said",
      "his desk",
    ],
    focus: "D reaches E. K reaches I. Bounce back to home after each reach.",
  },
  {
    id: "w2-ru",
    title: "Index up R and U",
    week: 2,
    keys: "asdfghjkl;eiru",
    words: [
      "far",
      "jar",
      "fur",
      "rule",
      "sure",
      "read",
      "full",
      "dark",
      "risk",
      "usual",
      "a real file",
      "sure deal",
      "dark red",
    ],
    focus: "F reaches R. J reaches U. Do not peek. Guess, then check the screen.",
  },
  {
    id: "w2-ty",
    title: "Index up T and Y",
    week: 2,
    keys: "asdfghjkl;eiruty",
    words: [
      "the",
      "they",
      "that",
      "yet",
      "stay",
      "task",
      "yes",
      "try",
      "just",
      "study",
      "the key",
      "they said",
      "try this",
    ],
    focus: "F reaches T. J reaches Y. These are the last home-adjacent letters.",
  },
  {
    id: "w2-all-letters",
    title: "All letters, still slow",
    week: 2,
    keys: "abcdefghijklmnopqrstuvwxyz",
    words: [
      "the quick",
      "type this",
      "home row",
      "next key",
      "slow and sure",
      "keep eyes up",
      "do not peek",
      "muscle memory",
      "code later",
    ],
    focus: "Full alphabet. Speed will feel worse. That is expected. Accuracy is the win.",
  },
  {
    id: "w3-shift",
    title: "Shift and capitals",
    week: 3,
    keys: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ",
    words: [
      "Python",
      "True",
      "False",
      "None",
      "Def",
      "Class",
      "The File",
      "A List",
      "Next Line",
    ],
    focus: "Opposite pinky holds Shift. Left Shift for right-hand letters, and the reverse.",
  },
  {
    id: "w3-punct",
    title: "Punctuation for code",
    week: 3,
    keys: "abcdefghijklmnopqrstuvwxyz()[]{}:.,_\"'",
    words: [
      "print()",
      "len(x)",
      "a, b, c",
      "x: int",
      "d[0]",
      "n = 1",
      "ok.",
      "name_1",
      "'hi'",
      '"ok"',
      "{a: 1}",
    ],
    focus: "Pinkies own most punctuation. Return to ; and A after every reach.",
  },
  {
    id: "w3-numbers",
    title: "Number row",
    week: 3,
    keys: "abcdefghijklmnopqrstuvwxyz0123456789",
    words: [
      "range(10)",
      "x = 2",
      "n = 40",
      "for i in 3",
      "year 2026",
      "wpm 40",
      "line 1",
    ],
    focus: "Each finger goes straight up from home. 5 and 6 are the index stretch.",
  },
  {
    id: "w4-python",
    title: "Python lines",
    week: 4,
    keys: "abcdefghijklmnopqrstuvwxyz0123456789()[]{}:.,_\"'=<> ",
    words: [
      "def add(a, b):",
      "return a + b",
      "for i in range(10):",
      "print(i)",
      "if x is None:",
      "items = [1, 2, 3]",
      "name = 'src'",
      "x == y",
      "x != y",
    ],
    focus: "This is the real goal: write code without hunting for keys.",
  },
  {
    id: "w4-average",
    title: "Average-speed builder",
    week: 4,
    keys: "abcdefghijklmnopqrstuvwxyz .,;:'\"",
    words: [
      "keep your eyes on the screen",
      "ten minutes is enough if you never look down",
      "accuracy first then speed follows",
      "return every finger to home row",
      "average typing speed is forty words a minute",
      "you type to think not to hunt keys",
    ],
    focus: "Full sentences. Stay above 95% accuracy. Speed is a side effect.",
  },
];

export const KEY_ROWS: KeyMeta[][] = [
  [
    { label: "`", finger: "Left pinky" },
    { label: "1", finger: "Left pinky" },
    { label: "2", finger: "Left ring" },
    { label: "3", finger: "Left middle" },
    { label: "4", finger: "Left index" },
    { label: "5", finger: "Left index" },
    { label: "6", finger: "Right index" },
    { label: "7", finger: "Right index" },
    { label: "8", finger: "Right middle" },
    { label: "9", finger: "Right ring" },
    { label: "0", finger: "Right pinky" },
    { label: "-", finger: "Right pinky" },
    { label: "=", finger: "Right pinky" },
  ],
  [
    { label: "q", finger: "Left pinky" },
    { label: "w", finger: "Left ring" },
    { label: "e", finger: "Left middle" },
    { label: "r", finger: "Left index" },
    { label: "t", finger: "Left index" },
    { label: "y", finger: "Right index" },
    { label: "u", finger: "Right index" },
    { label: "i", finger: "Right middle" },
    { label: "o", finger: "Right ring" },
    { label: "p", finger: "Right pinky" },
    { label: "[", finger: "Right pinky" },
    { label: "]", finger: "Right pinky" },
  ],
  [
    { label: "a", finger: "Left pinky", home: true },
    { label: "s", finger: "Left ring", home: true },
    { label: "d", finger: "Left middle", home: true },
    { label: "f", finger: "Left index", home: true },
    { label: "g", finger: "Left index" },
    { label: "h", finger: "Right index" },
    { label: "j", finger: "Right index", home: true },
    { label: "k", finger: "Right middle", home: true },
    { label: "l", finger: "Right ring", home: true },
    { label: ";", finger: "Right pinky", home: true },
    { label: "'", finger: "Right pinky" },
  ],
  [
    { label: "z", finger: "Left pinky" },
    { label: "x", finger: "Left ring" },
    { label: "c", finger: "Left middle" },
    { label: "v", finger: "Left index" },
    { label: "b", finger: "Left index" },
    { label: "n", finger: "Right index" },
    { label: "m", finger: "Right index" },
    { label: ",", finger: "Right middle" },
    { label: ".", finger: "Right ring" },
    { label: "/", finger: "Right pinky" },
  ],
  [{ label: " ", finger: "Thumbs" }],
];

export const FINGER_BY_KEY: Record<string, string> = {};
for (const row of KEY_ROWS) {
  for (const key of row) {
    FINGER_BY_KEY[key.label] = key.finger;
  }
}

export const FINGER_MAP: string[][] = [
  ["Left pinky", "A", "` 1 q a z"],
  ["Left ring", "S", "2 w s x"],
  ["Left middle", "D", "3 e d c"],
  ["Left index", "F", "4 5 r t f g v b"],
  ["Thumbs", "Space", "spacebar"],
  ["Right index", "J", "6 7 y u h j n m"],
  ["Right middle", "K", "8 i k ,"],
  ["Right ring", "L", "9 o l ."],
  ["Right pinky", ";", "0 - = p [ ] \\ ; ' /"],
];

export function lessonNumber(id: string): number {
  const index = LESSONS.findIndex((lesson) => lesson.id === id);
  return index === -1 ? 1 : index + 1;
}
